<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-14T19:23:42 BOT" name="Suite" finished-at="2022-04-14T19:23:42 BOT" duration-ms="106">
    <groups>
    </groups>
    <test started-at="2022-04-14T19:23:42 BOT" name="Test" finished-at="2022-04-14T19:23:42 BOT" duration-ms="106">
      <class name="ivanmaventest.Mavenjava.RESTAPITest">
        <test-method signature="DeleteTweet()[pri:0, instance:ivanmaventest.Mavenjava.RESTAPITest@1f3f4916]" started-at="2022-04-14T19:23:42 BOT" name="DeleteTweet" finished-at="2022-04-14T19:23:42 BOT" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteTweet -->
        <test-method signature="PostJira()[pri:0, instance:ivanmaventest.Mavenjava.RESTAPITest@1f3f4916]" started-at="2022-04-14T19:23:42 BOT" name="PostJira" finished-at="2022-04-14T19:23:42 BOT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostJira -->
      </class> <!-- ivanmaventest.Mavenjava.RESTAPITest -->
      <class name="ivanmaventest.Mavenjava.AppiumTest">
        <test-method signature="IOSApp()[pri:0, instance:ivanmaventest.Mavenjava.AppiumTest@5cee5251]" started-at="2022-04-14T19:23:42 BOT" name="IOSApp" finished-at="2022-04-14T19:23:42 BOT" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at ivanmaventest.Mavenjava.AppiumTest.IOSApp(AppiumTest.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IOSApp -->
        <test-method signature="NativeAPPAndroid()[pri:0, instance:ivanmaventest.Mavenjava.AppiumTest@5cee5251]" started-at="2022-04-14T19:23:42 BOT" name="NativeAPPAndroid" finished-at="2022-04-14T19:23:42 BOT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NativeAPPAndroid -->
      </class> <!-- ivanmaventest.Mavenjava.AppiumTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
